"""Deterministic offline stubs for `make demo`.

Used whenever `GROQ_API_KEY` is unset. Produces well-formed plan/outline/
article/image-prompt objects so the rest of the pipeline can be exercised
end-to-end without burning credits or hitting the network.
"""

from __future__ import annotations

import re
from typing import Any


def _slug(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s)
    return s[:60].strip("-")


def stub_plan(topic: str, language: str) -> dict[str, Any]:
    slug = _slug(topic)
    return {
        "title": f"{topic}: A Practical Guide",
        "slug": slug,
        "meta_description": f"A practical introduction to {topic}, with examples, gotchas, and a short FAQ.",
        "focus_keyword": topic.lower(),
        "secondary_keywords": [f"{topic} guide", f"how to {topic.lower()}", f"{topic} examples"],
        "target_audience": "practitioners exploring the topic for the first time",
        "content_angle": "answer-first explanation grounded in concrete examples",
        "language": language,
        "_engine": "offline-stub",
    }


def stub_outline(plan: dict[str, Any]) -> list[dict[str, Any]]:
    topic = plan["focus_keyword"]
    return [
        {"h2": f"What is {topic}?", "points": [
            "Plain-language definition", "Closest analogue", "Why it matters in practice",
        ]},
        {"h2": "How it works", "points": [
            "The core mechanism", "Inputs and outputs", "Common configurations",
        ]},
        {"h2": "Where it shines", "points": [
            "Use cases", "Real-world examples", "Measurable outcomes",
        ]},
        {"h2": "Common pitfalls", "points": [
            "Setup mistakes", "Maintenance traps", "How to avoid each",
        ]},
        {"h2": "Getting started", "points": [
            "Minimal first step", "Tools you'll need", "What to measure",
        ]},
    ]


def stub_article(plan: dict[str, Any], outline: list[dict[str, Any]]) -> str:
    """Renders the outline into a markdown article using static prose templates."""
    lines = [f"# {plan['title']}", "", plan["meta_description"], ""]
    for section in outline:
        lines.append(f"## {section['h2']}")
        lines.append("")
        for p in section["points"]:
            lines.append(
                f"{p.capitalize()}. This is a demo paragraph generated by the offline stub — "
                f"in live mode, an LLM expands each point into 40–80 words of concrete prose."
            )
            lines.append("")
    lines.extend([
        "## FAQ",
        "",
        f"**Q: Is {plan['focus_keyword']} hard to get started with?**",
        "A: No — the minimum viable setup fits in a single afternoon.",
        "",
        f"**Q: What's the most common mistake?**",
        "A: Skipping measurement and only revisiting the setup when something breaks.",
        "",
        f"**Q: What tooling do you recommend?**",
        "A: Start with whatever already lives in your stack; swap once you hit a real limit.",
        "",
    ])
    return "\n".join(lines)


def stub_image_prompts(plan: dict[str, Any]) -> dict[str, str]:
    topic = plan["focus_keyword"]
    return {
        "hero": f"editorial hero image about {topic}, photographic, 16:9, soft daylight",
        "info": f"clean infographic about {topic}, flat vector style, two muted accent colors",
        "photo": f"lifestyle photo loosely related to {topic}, natural lighting, single subject",
    }
